<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;
    protected $fillable = [
        'logo',
        'logo_admin',
        'favicon',
        'counter_bg',
        'login_bg',
        'footer_copyright',
        'footer_address',
        'footer_phone',
        'footer_working_hour',
        'footer_address_icon',
        'footer_phone_icon',
        'footer_working_hour_icon',
        'footer_about',
        'top_bar_email',
        'top_bar_phone',
        'contact_map_iframe',
        'send_email_from',
        'receive_email_to',
        'smtp_active',
        'smtp_ssl',
        'smtp_host',
        'smtp_port',
        'smtp_username',
        'smtp_password',
        'total_recent_post',
        'total_popular_post',
        'total_recent_post_home',
        'theme_color_1',
        'theme_color_2',
        'counter1_text',
        'counter1_value',
        'counter2_text',
        'counter2_value',
        'counter3_text',
        'counter3_value',
        'counter4_text',
        'counter4_value',
        'counter_status',
        'banner_about',
        'banner_faq',
        'banner_gallery',
        'banner_service',
        'banner_portfolio',
        'banner_testimonial',
        'banner_news',
        'banner_contact',
        'banner_search',
        'banner_category',
        'banner_terms',
        'banner_privacy',
        'why_choose_title',
        'why_choose_subtitle',
        'why_choose_status',
        'service_title',
        'service_subtitle',
        'service_status',
        'portfolio_title',
        'portfolio_subtitle',
        'portfolio_status',
        'team_title',
        'team_subtitle',
        'team_status',
        'testimonial_title',
        'testimonial_subtitle',
        'testimonial_status',
        'faq_title',
        'faq_subtitle',
        'faq_status',
        'gallery_title',
        'gallery_subtitle',
        'gallery_status',
        'recent_post_title',
        'recent_post_subtitle',
        'recent_post_status',
        'partner_title',
        'partner_subtitle',
        'partner_status',
        'preloader_status',
        'faq_main_photo',
        'testimonail_main_photo',
        'why_choose_main_photo',
        'why_choose_item_bg',
        'tawk_live_chat_code',
        'tawk_live_chat_status',
    ];
}
